version: '3.3'

networks:
  bridge_network:
    external: true

volumes:
  mysql:

secrets:
  mysql_user:
      external: true


services:
 mysql:
  image: local/mysql:latest
  networks:
   - bridge_network
  deploy:
    replicas: 1
  volumes:
   - /Users/i326049/Documents/GitHub/persistence/mysql:/var/lib/mysql
  secrets:
    - source: mysql_user
      target: mysql_user
      uid: '103'
      gid: '103'
      mode: 0440
 mediawiki:
  image: local/mediawiki:latest
  networks:
   - bridge_network
  deploy:
    replicas: 1
  volumes:
   - /Users/i326049/Documents/GitHub/persistence/mediawiki:/config
  secrets:
    - source: mysql_user
      target: mysql_user
      uid: '103'
      gid: '103'
      mode: 0440
  ports:
   - 80:80

