version: '3.3'

networks:
  bridge_network:
    external: true

volumes:
  mysql:

services:
## Elastic search and fluentd global services
 mysql:
  image: local/mysql:latest
  networks:
   - bridge_network
  deploy:
    replicas: 1
  volumes:
   - /Users/i326049/Documents/GitHub/persistence/mysql:/var/lib/mysql
  environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD=yes
 mediawiki:
  image: local/mediawiki:latest
  networks:
   - bridge_network
  deploy:
    replicas: 1
  volumes:
   - /Users/i326049/Documents/GitHub/persistence/mediawiki:/config
  ports:
   - 80:80

